### PR TITLE
fix(schematics): fix tsconfig in scully folder to actually work

### LINKED ISSUE #907: Typescript error while compiling plugins. scully/**/*.ts' not found scully/*.ts' not found
Just updated my project from angular 5 to angular 10 so I can implement scully io. 

After doing the following on a angular 10.1.0 project 

``` 
ng add @scullyio/init 
ng build
npm run scully
```

I get the following error: 

Typescript error while compiling plugins. the error is:
error TS6053: File 'C:/cmder/development/<project_name>/scully/**/*.ts' not found.
error TS6053: File 'C:/cmder/development/<project_name>/scully/*.ts' not found.

Looking at the tsconfig.sjon in the ./scully folder looks like its configured to look for the following:

Annotation 2020-09-04 181255

I have tried commenting out the files property but it just thrown other error. Any ideal?

After further looking into this it seems I can reproduce this with a fresh generation of a angular project.

Here is my versions

Angular CLI: 10.1.0                                    
Node: 12.13.1                                          
OS: win32 x64                                          
                                                       
Angular:                                               
...                                                    
Ivy Workspace:                                         
                                                       
Package                      Version                   
------------------------------------------------------ 
@angular-devkit/architect    0.1001.0                  
@angular-devkit/core         10.1.0                    
@angular-devkit/schematics   10.1.0                    
@schematics/angular          10.1.0                    
@schematics/update           0.1001.0                  
rxjs                                        6.6.2                      

The process for reproduce are:

``` 
ng new my-app
cd my-app\
ng build
 npm run scully

```

The following error happens:

using plugins from folder "./scully"
Typescript error while compiling plugins. the error is:
error TS6053: File 'C:/cmder/development/my-app/scully/**/*.ts' not found.
error TS6053: File 'C:/cmder/development/my-app/scully/*.ts' not found.

⠹ undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! my-app@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the my-app@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hubbe\AppData\Roaming\npm-cache\_logs\2020-09-05T15_01_39_356Z-debug.log

### PR DESCRIPTION
**Pull request by SanderElias**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: closed #907

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
@jorge I already published this to NPM, can you double-check my work?

File: libs/scully-schematics/src/plugin-ts/index.ts [hunk 1]
```diff
@@ -61,8 +57,8 @@ const updateScullyConfig = (options: Schema) => (tree: Tree, context: SchematicC
   if (!scullyJs) {
     context.logger.error(`No scully configuration file found ${scullyConfigFile}`);
   }
-  const newScullyJs = addTypescriptFolder(scullyJs, `pluginDir: './scully/plugins/'`);
+  // const newScullyJs = addTypescriptFolder(scullyJs, `pluginDir: './scully/plugins/'`);
 
-  tree.overwrite(scullyConfigFile, newScullyJs);
-  context.logger.info(`✅️ Update ${scullyConfigFile}`);
+  // tree.overwrite(scullyConfigFile, newScullyJs);
+  // context.logger.info(`✅️ Update ${scullyConfigFile}`);
```
Comment (jorgeucano) [inline libs/scully-schematics/src/plugin-ts/index.ts:63]: YOu need the newScully for replace the file (or add) and the logger for show the message

**Review by jorgeucano — APPROVED** [review]
